2021-07-27 11:25:01,958 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 2802, half = 0
2021-07-27 11:25:01,958 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157AC66BBC8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:25:26,820 - get_team_names.py[line:26] - WARNING: get team names failed: http://data.champdas.com/match/data-2811.html
2021-07-27 11:25:26,820 - get_team_names.py[line:27] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /match/data-2811.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157AC4566C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-27 11:27:00,689 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 2964, half = 1
2021-07-27 11:27:00,689 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157ADC6B548>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
