2021-07-26 23:22:37,819 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 2785, half = 0
2021-07-26 23:22:37,819 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A0F24948>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:24:11,390 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchStaticListAjax.html, match_id = 2942, half = 0
2021-07-26 23:24:11,391 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchStaticListAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A1989348>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:25:46,947 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 1536, half = 2
2021-07-26 23:25:46,947 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E29FDC2448>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:26:41,466 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchStaticListAjax.html, match_id = 1609, half = 2
2021-07-26 23:26:41,467 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchStaticListAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A113A388>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:27:03,623 - get_team_names.py[line:26] - WARNING: get team names failed: http://data.champdas.com/match/data-1662.html
2021-07-26 23:27:03,623 - get_team_names.py[line:27] - WARNING: 404 Client Error: Not Found for url: http://data.champdas.com/match/data-1662.html
2021-07-26 23:27:27,954 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 1669, half = 1
2021-07-26 23:27:27,954 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A13E1808>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:29:21,884 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 15090, half = 1
2021-07-26 23:29:21,884 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E29FFC37C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:29:55,319 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 15119, half = 1
2021-07-26 23:29:55,320 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A0CC71C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:32:41,808 - get_team_names.py[line:26] - WARNING: get team names failed: http://data.champdas.com/match/data-16148.html
2021-07-26 23:32:41,808 - get_team_names.py[line:27] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /match/data-16148.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A07D0948>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:33:41,193 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 16231, half = 0
2021-07-26 23:33:41,193 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A0B02F88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:34:26,854 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 16285, half = 2
2021-07-26 23:34:26,854 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A1103C48>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:35:51,829 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchDefencesRateAjax.html, match_id = 16595, half = 2
2021-07-26 23:35:51,829 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchDefencesRateAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E29FF086C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:36:55,311 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchStaticListAjax.html, match_id = 16682, half = 1
2021-07-26 23:36:55,322 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchStaticListAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E2A16DA2C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:37:43,070 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 16740, half = 0
2021-07-26 23:37:43,070 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E29FBD5208>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
2021-07-26 23:38:37,267 - get_json_data.py[line:49] - WARNING: get json data failed: ajax_url = http://data.champdas.com/getMatchAttackAjax.html, match_id = 17349, half = 0
2021-07-26 23:38:37,267 - get_json_data.py[line:50] - WARNING: HTTPConnectionPool(host='data.champdas.com', port=80): Max retries exceeded with url: /getMatchAttackAjax.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002E29FC0BF08>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
